name: Check & deploy API documentation
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  deploy-doc:
    environment: prod
    name: Deploy API documentation on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: '.nvmrc'
      
      - name: install bump
        run: npm install -g bump-cli

      - name: validate open api
        run: |
         bump deploy --dry-run \
            --doc "dataminersite" \
            --token "${{ secrets.BUMP_TOKEN }}" \
            doc/openapi.yaml
