name: Update swagger

on:
    workflow_dispatch:

jobs:
  deploy-doc:
    environment: prod
    name: Deploy API documentation on Bump.sh
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: download yaml swagger doc
        run: curl ${{vars.API_URL}} -o doc/openapi.yaml

      - name: commit the doc
        uses: stefanzweifel/git-auto-commit-action@v5
        