name: Update swagger

on:
    workflow_dispatch:
    workflow_call:
    schedule:
        - cron: "0 * * * *"

jobs:
  pull-doc:
    environment: prod
    name: pull api url from docker
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: download yaml swagger doc
        run: curl ${{vars.API_URL}} -o doc/openapi.yaml

      - name: commit the doc
        uses: stefanzweifel/git-auto-commit-action@v5


  bump_io_deploy:
    environment: prod
    name: deploy api doc to prod
    needs: pull-doc
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      issues: write
    steps:
      - name: Checkout
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: bump.yml
          token: ${{ secrets.MY_GITHUB_TOKEN }}
